blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', views.index, name='index'),
    path('revistas/', views.lista_revistas, name='lista_revistas'),
    path('posts/lista/', views.post_list, name='post_list'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('posts/principal/', views.post_principal, name='post_principal'),
    path('posts/recitales/', views.post_recitales, name='post_recitales'),
    path('posts/reseñas/', views.post_reseñas, name='post_reseñas'),
    path('posts/que_es_la_reehm/', views.post_que_es_la_reehm, name='post_que_es_la_reehm'),
    path('posts/protocolo/', views.post_protocolo, name='protocolo'),
    path('posts/encuentros/', views.post_encuentros, name='post_encuentros'),
    path('posts/agenda/', views.post_agenda, name='post_agenda'),
    path('posts/publicaciones/', views.publicaciones, name='publicaciones'),
    path('posts/quienes_somos/', views.quienes_somos, name='quienes_somos'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reehm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.core.files.storage import default_storage

class Post(models.Model):
    SECTIONS = [
        ('que_es_la_reehm', '¿Qué es la Reehm?'),
        ('protocolo', 'Protocolo'),
        ('encuentros', 'Encuentros'),
        ('reseñas', 'Reseñas'),
        ('agenda', 'Agenda'),
    ]

    title = models.CharField(max_length=200, verbose_name='Título')
    text = models.TextField(verbose_name='Texto')
    image = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Imagen Principal')
    image_2 = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Imagen Secundaria 1')
    image_3 = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Imagen Secundaria 2')
    image_4 = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Imagen Secundaria 3')
    author = models.CharField(max_length=200, verbose_name='Autor')
    section = models.CharField(max_length=50, choices=SECTIONS, default='principal', verbose_name='Sección')
    slug = models.SlugField(unique=True, blank=True, max_length=200, verbose_name='Slug (puedes dejarlo en blanco y se genera sólo)')
    date_published = models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')
    carrusel = models.BooleanField(default=False, verbose_name='Principal en Carrusel')
    importante = models.BooleanField(default=False, verbose_name='Principal en Importante')
    otras = models.BooleanField(default=False, verbose_name='Principal en Otras')

    def publish(self):
        self.date_published = timezone.now()
        self.save()

    def save(self, *args, **kwargs):
        if not self.pk:
            if not self.author:
                self.author = User.objects.filter(username='Reem').first()  
                if not self.author:
                    # Crea el usuario si no existe
                    self.author = User.objects.create_user(username='Reehm', password='defaultpassword')
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Elimina los archivos de imagen antes de eliminar la instancia
        if self.image and default_storage.exists(self.image.path):
            default_storage.delete(self.image.path)
        if self.image_2 and default_storage.exists(self.image_2.path):
            default_storage.delete(self.image_2.path)
        if self.image_3 and default_storage.exists(self.image_3.path):
            default_storage.delete(self.image_3.path)
        if self.image_4 and default_storage.exists(self.image_4.path):
            default_storage.delete(self.image_4.path)
        
        super().delete(*args, **kwargs)

    def _str_(self):
        return self.title

class Revista(models.Model):
    titulo = models.CharField(max_length=200, verbose_name='Título')
    imagen = models.ImageField(upload_to='revistas/imagenes/', verbose_name='Imagen de la Revista')
    archivo_pdf = models.FileField(upload_to='revistas/pdfs/', verbose_name='Archivo PDF')

    def __str__(self):
        return self.titulo

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post
from django.templatetags.static import static
import os
from django.conf import settings
from django.shortcuts import render
from .models import Revista


def post_list(request):
    posts = Post.objects.filter(date_published__lte=timezone.now()).order_by('date_published')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    
    # Divide el texto en párrafos
    paragraphs = post.text.split('\n')
    total_paragraphs = len(paragraphs)
    third = total_paragraphs // 3
    
    # Divide los párrafos en tres partes
    part1 = paragraphs[:third]
    part2 = paragraphs[third:2*third]
    part3 = paragraphs[2*third:]
    
    context = {
        'post': post,
        'part1': part1,
        'part2': part2,
        'part3': part3,
    }
    return render(request, 'blog/post_detail.html', context)

def post_principal(request):
    posts = Post.objects.filter(section='principal').order_by('-date_published')
    return render(request, 'blog/post_principal.html', {'posts': posts})

def post_recitales(request):
    posts = Post.objects.filter(section='recitales').order_by('-date_published')
    return render(request, 'blog/post_recitales.html', {'posts': posts})

def post_reseñas(request):
    posts = Post.objects.filter(section='reseñas').order_by('-date_published')
    return render(request, 'blog/post_reseñas.html', {'posts': posts})

def post_que_es_la_reehm(request):
    posts = Post.objects.filter(section='que_es_la_reehm').order_by('-date_published')
    return render(request, 'blog/post_que_es_la_reehm.html', {'posts': posts})

def post_protocolo(request):
    return render(request, 'blog/post_protocolo.html')

def quienes_somos(request):
    return render(request, 'blog/quienes_somos.html')

def post_encuentros(request):
    posts = Post.objects.filter(section='encuentros').order_by('-date_published')
    return render(request, 'blog/post_encuentros.html', {'posts': posts})

def post_agenda(request):
    posts = Post.objects.filter(section='agenda').order_by('-date_published')
    return render(request, 'blog/post_agenda.html', {'posts': posts})

def lista_revistas(request):
    revistas = Revista.objects.all()
    return render(request, 'blog/lista_revistas.html', {'revistas': revistas})

def index(request):
    # Obtener publicaciones que se mostrarán en el carrusel
    carrusel_posts = Post.objects.filter(carrusel=True)
    # Obtener publicaciones importantes
    importante_posts = Post.objects.filter(importante=True)
    # Obtener otras publicaciones
    otras_posts = Post.objects.filter(otras=True)

    context = {
        'carrusel_posts': carrusel_posts,
        'importante_posts': importante_posts,
        'otras_posts': otras_posts,
    }
    return render(request, 'blog/index.html', context)

def publicaciones(request):
    # Obtenemos todas las revistas desde la base de datos
    revistas = Revista.objects.all()
    
    # Renderizamos el template con las revistas
    return render(request, 'blog/publicaciones.html', {'revistas': revistas})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>REEHM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <style>
        body {
            background-color: #000000; 
        }
        .footer {
            max-width: 100%;
            background-color: #000000; 
            padding: 10px;
            text-align: right;
        }
        .footer a {
            color: #505050; 
            transition: color 0.3s;
        }
        .footer a:hover {
            color: #999999; 
        }
    </style>
</head>
<body style= "max-width: 99.5%; padding: 0.5%">
    {% include 'blog/navbar.html' %}
    {% block content %}
    {% endblock %}
    <footer class="footer">
        <a href="https://www.instagram.com/reehm_argentina/" target="_blank" style="text-decoration: none; margin-right: 10px;">
            <i class="fab fa-instagram fa-2x"></i>
        </a><a href="https://www.youtube.com/your_channel" target="_blank" style="text-decoration: none; margin-right: 10px;">
            <i class="fab fa-youtube fa-2x"></i>
        </a>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<style>
    body {
        background-color: #000000; 
    }
    .carousel {
        padding: 1vh;
        width: 100%;
        height: 50vh;
    }
    .carousel-item {
        height: 100%;
    }
    .carousel-item img {
        object-fit: cover;
        width: 100%;
        height: 100%;
        display: block;
    }
    .carousel-inner {
        width: 100%;
        height: 100%;
    }
    .carousel-caption {
        background-color: rgba(0, 0, 0, 0.5);
        padding: 20px;
        text-align: left;
    }
    .carousel-caption h1 {
        font-size: 2.5rem;
        color: #ffffff;
        font-family: 'Arial', sans-serif;
        text-align: center;
    }
    .titulo {
        text-align: center;
    }
    .carousel-caption p {
        color: #ffffff;
        padding-top: 10px;
        font-size: 1rem;
    }
    .share-button {
        padding-top: 10px;
        color: #ffffff;
        border: 1px solid #ffffff;
        background-color: transparent;
        padding: 5px 10px;
        font-size: 1rem;
        cursor: pointer;
    }
    .important-posts {
        width: 100%;
        padding-top: 2vh;
    }
    .important-post {
        padding: 20px;
        position: relative;
        background-color: #f0f0f0; 
        border-radius: 10px; 
        margin-bottom: 20px;
    }
    .important-post img {
        width: 100%;
        max-height: 30vh;
        object-fit: cover;
        border-radius: 10px 10px 0 0; 
    }
    .important-post .section-label {
        position: absolute;
        top: 10px;
        left: 10px;
        background-color: rgba(0, 0, 0, 0.7);
        color: #ffffff;
        padding: 5px 10px;
        font-size: 0.8rem;
        border-radius: 3px;
    }
    .other-posts {
        padding-top: 2vh;
    }
    .other-post {
        padding: 20px;
        background-color: #f0f0f0; 
        border-radius: 10px; 
        margin-bottom: 20px;
    }
    .other-post img {
        width: 100%;
        max-height: 20vh;
        object-fit: cover;
        border-radius: 10px 10px 0 0;
    }
    .read-more-link {
        color: #000000;
        text-decoration: none;
        font-style: oblique;
    }
    .read-more-link:hover {
        text-decoration: underline;
    }
</style>

{% if carrusel_posts %}
<div id="carouselExampleCaptions" class="carousel slide">
    <div class="carousel-inner">
        {% for post in carrusel_posts %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
            {% if post.image %}
            <a href="{% url 'post_detail' slug=post.slug %}">
                <img src="{{ post.image.url }}" alt="{{ post.title }}">
            </a>
            {% endif %}
            <div class="carousel-caption d-none d-md-block">
                <h1 class="titulo">
                    <a href="{% url 'post_detail' slug=post.slug %}" style="color: #ffffff; text-decoration: none;">{{ post.title }}</a>
                </h1>
                <p>Por: <b>{{ post.author }}</b> | {{ post.text|truncatewords:40 }} 
                    <a href="{% url 'post_detail' slug=post.slug %}" class="read-more-link">leer más</a>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
{% endif %}

<!-- Importante -->
{% if importante_posts %}
<div class="important-posts">
    <div class="row">
        {% for post in importante_posts %}
        <div class="col-md-4">
            <div class="important-post">
                {% if post.image %}
                <a href="{% url 'post_detail' slug=post.slug %}">
                    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                </a>
                <div class="section-label">{{ post.get_section_display }}</div>
                {% endif %}
                <h2 class="titulo">
                    <a href="{% url 'post_detail' slug=post.slug %}" style="color: #000000; text-decoration: none;">{{ post.title }} | Por: <b>{{ post.author }}</b></a>
                </h2>
                <p>{{ post.text|truncatewords:40 }} 
                    <a href="{% url 'post_detail' slug=post.slug %}" class="read-more-link" style="color: #000000;">leer más</a>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

<!-- Otras -->
{% if otras_posts %}
<div class="other-posts">
    <div class="row">
        {% for post in otras_posts %}
        <div class="col-md-3">
            <div class="other-post">
                {% if post.image %}
                <a href="{% url 'post_detail' slug=post.slug %}">
                    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                </a>
                {% endif %}
                <h2 class="titulo">
                    <a href="{% url 'post_detail' slug=post.slug %}" style="color: #000000; text-decoration: none;">{{ post.title }}</a>
                </h2>
                <p>{{ post.text|truncatewords:40 }} 
                    <a href="{% url 'post_detail' slug=post.slug %}" class="read-more-link" style="color: #000000;">leer más</a>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

<script>
    function copyToClipboard(url) {
        navigator.clipboard.writeText(url).then(function() {
            alert('¡Enlace copiado al portapapeles!');
        }, function(err) {
            alert('Error al copiar el enlace: ', err);
        });
    }
</script>
{% endblock %}

blog/templates/blog/navbar.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>REEHM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <style>
       .navbar {
            background-image: url("{% static 'images/ondas.png' %}");
            background-position: center;
            background-repeat: repeat;
            background-size: contain; /* Ajusta la imagen para que no se deforme */
            background-color: #f8f9fa; /* Puedes añadir un color de fondo para rellenar espacios */
        }
        .navbar-nav .nav-link {
          color: white !important; 
          font-weight: bold; 
          margin: 1px;
          background-color: rgba(144, 144, 144, 0.2);
          border-radius: 0.25rem; 
          padding: 0.5rem 1rem; 
          transition: background-color 0.3s, color 0.3s; 
        }
        
        .navbar-nav .nav-link.active {
            color: #fff !important; 
        }      
        
        .navbar-nav .nav-link:hover {
            color: #333; 
            background-color: rgba(224, 224, 224, 0.5); 
        }
        body {
            background-color: #000000; 
            color:#fff;
        }
      
    </style>
</head>
<body>
    <div class="page-header" style="max-width: 100%;">
        <nav class="navbar navbar-expand-xl navbar-light" style="padding: 0;">
            <div class="container-fluid" style="padding: 0;">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">
                                <i class="fa fa-home" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'publicaciones' %}">Publicaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'post_reseñas' %}">Reseñas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'post_que_es_la_reehm' %}">¿Qué es la Reehm?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'protocolo' %}">Protocolo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'post_encuentros' %}">Encuentros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'post_agenda' %}">Agenda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quienes_somos' %}">¿Quienes somos?</a>
                        </li>
                    </ul>
                </div>
            </div>
            <h1>
                <a class="navbar-brand" href="{% url 'index' %}">REEHM</a>
            </h1>
        </nav>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/post_agenda.html
{% extends 'blog/post_reseñas.html' %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        padding: 20px;
        line-height: 1.6;
        background-color: #000000; 
        
    }

    .titulo_nota {
        text-align: center;
        background-color: #f0f0f0;
        padding: 10px;
        border-radius: 5px;
    }

    .post-info {
        text-align: center;
        margin-bottom: 20px;
        color: #666;
    }

    .image-main, .image-secondary img {
        display: block;
        margin: 20px auto;
        max-width: 100%;
        height: auto; 
    }

    .text-content {
        padding: 20vh;
        position: relative;
    }

    .text-section {
        padding-bottom: 20px; 
        text-align: justify; 
    }

    .clearfix::after {
        content: "";
        clear: both;
        display: table;
    }
</style>

<h1 class="titulo_nota">{{ post.title }}</h1>
<p class="post-info">Sección: {{ post.get_section_display }} | Fecha: {{ post.date_published|date:"d/m/Y" }} | Autor: {{ post.author }}</p>

{% if post.image %}
    <img src="{{ post.image.url }}" alt="Imagen principal" class="image-main">
{% endif %}

<div class="text-content">
    <!-- Primer tercio -->
    <div class="text-section">
        {% for paragraph in part1 %}
            <p>{{ paragraph }}</p>
        {% endfor %}
    </div>

    <!-- Imagen secundaria 1 -->
    {% if post.image_2 %}
        <div class="image-secondary">
            <img src="{{ post.image_2.url }}" alt="Imagen secundaria 1">
        </div>
    {% endif %}

    <!-- Segundo tercio -->
    <div class="text-section">
        {% for paragraph in part2 %}
            <p>{{ paragraph }}</p>
        {% endfor %}
    </div>

    <!-- Imagen secundaria 2 -->
    {% if post.image_3 %}
        <div class="image-secondary">
            <img src="{{ post.image_3.url }}" alt="Imagen secundaria 2">
        </div>
    {% endif %}

    <!-- Tercer tercio -->
    <div class="text-section">
        {% for paragraph in part3 %}
            <p>{{ paragraph }}</p>
        {% endfor %}
    </div>
</div>

<!-- Imagen secundaria 3 -->
{% if post.image_4 %}
    <div class="image-secondary">
        <img src="{{ post.image_4.url }}" alt="Imagen secundaria 3">
    </div>
{% endif %}
{% endblock %}

blog/templates/blog/post_encuentros.html
{% extends 'blog/post_reseñas.html' %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h2><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_principal.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.date_published|date:"d/m/Y" }}
            </div>
            <h2><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_que_es_la_reehm.html
{% extends 'blog/base.html' %}

blog/templates/blog/post_recitales.html
{% extends 'blog/post_reseñas.html' %}

blog/templates/blog/post_reseñas.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="section-title">{{ posts.first.get_section_display }}</h1>

    <div class="row">
        {% for post in posts %}
        <div class="col-md-6">
            <div class="post mb-4 p-3" style="background-color: #f0f0f0; border-radius: 8px; overflow: hidden;">
                {% if post.image %}
                <div class="post-image position-relative" style="height: 40vh; overflow: hidden;">
                    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid w-100 h-100" style="object-fit: cover; max-height: 40vh;">
                    <h2 class="post-title position-absolute" style="bottom: 10px; left: 10px; color: white; background-color: rgba(0, 0, 0, 0.5); padding: 5px; border-radius: 5px;">
                        <a href="{% url 'post_detail' slug=post.slug %}" style="color: white; text-decoration: none;">{{ post.title }}</a>
                    </h2>
                </div>
                {% endif %}
                <div class="post-details mt-2">
                    <p class="post-meta">Por: <b>{{ post.author }}</b></p>
                    <p class="post-excerpt">{{ post.text|truncatewords:40 }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/publicaciones.html
{% extends 'blog/base.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Publicaciones</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Revistas</h1>
        <div class="row">
            {% for revista in revistas %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <img src="{{ revista.imagen.url }}" class="card-img-top" alt="Imagen de {{ revista.titulo }}" style="height: 200px; object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title">{{ revista.titulo }}</h5>
                    </div>
                    <div class="card-footer">
                        <a href="{{ revista.archivo_pdf.url }}" class="btn btn-primary" download>Descargar PDF</a>
                        <a href="{{ revista.archivo_pdf.url }}" class="btn btn-secondary" target="_blank">Ver en otra pestaña</a>
                                           
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

blog/templates/blog/quienes_somos.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}
    ¿Quiénes somos?
{% endblock %}

{% block content %}
    <style>
        .team-container {
            background-color: #000000; 
            color: white;
            padding: 40px 20px;
            text-align: center;
        }

        .team-title {
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 40px;
        }

        .history-section {
            margin-bottom: 60px;
            font-size: 18px;
            line-height: 1.6;
            max-width: 800px;
            margin-left: auto;
            margin-right: auto;
        }

        .team-members {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            gap: 40px;
        }

        .team-member {
            text-align: center;
            width: 200px;
        }

        .member-photo {
            width: 150px;
            height: 150px;
            border-radius: 50%;
            object-fit: cover;
            margin-bottom: 20px;
            border: 3px solid #fff;
        }

        .member-name {
            font-size: 20px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .member-bio {
            font-size: 16px;
        }
    </style>

    <div class="team-container">
        <h1 class="team-title">¿Qué es la REEHM?</h1>

        <div class="history-section">
            <p>
                REEHM es una iniciativa dedicada a la promoción de la diversidad y la inclusión en la escena metalera
                latinoamericana. Nacida en el año [Año de Fundación], nuestro objetivo ha sido siempre el de generar
                un espacio seguro y respetuoso para todos los participantes, con un especial énfasis en visibilizar
                las voces y experiencias de las mujeres, personas trans, y otros grupos marginados dentro de la cultura
                metal.
            </p>
            <p>
                A lo largo de los años, hemos trabajado incansablemente para fomentar la reflexión colectiva y la
                acción comunitaria, organizando rondas de brujxs, charlas y publicaciones que abordan temas de género,
                raza, clase y más. Nuestro equipo está conformado por personas apasionadas y comprometidas con esta
                causa, quienes día a día trabajan para hacer del metal un espacio más inclusivo para todxs.
            </p>
        </div>

        <div class="team-members">
            <div class="team-member">
            <img src="{% static 'images/banner.png' %}" alt="Descripción de la imagen">

                <div class="member-name">Eduardo</div>
                <div class="member-bio">
                    "El Heavy mi vida, Iorio mi pasión, pero siempre escuche los CD´s de los BSB de mi hermana a escondidas."
                </div>
            </div>

            <div class="team-member">
                <img style= "border-radius: 50%" src="{% static 'images/imagen1.png' %}" alt="Descripción de la imagen">

                <div class="member-name">Cosme Fulanito</div>
                <div class="member-bio">
                    Escritor, se inició en el heavy.. bla bla bla.
                </div>
            </div>

        </div>
    </div>
{% endblock %}